### ISSUE TITLE
Getting error="missing signature" - despite no secret being used

### ISSUE THREAD

**Issue by erikkerber** [palantir/bulldozer#166]
I'm doing some local testing of Bulldozer, and hoping to fire some test webhooks to localhost.

When I omit the `gitHub.app.webhook_secret` value, or even set it to "", I receive a `error="missing signature"` error when posting my test hook.

I expect Bulldozer to skip validation when the secret is omitted.

Relevant go-github line: https://github.com/google/go-github/blob/7c15ddab767f5a36d259f6565b88e82475842742/github/messages.go#L187

**Comment by bluekeyes** [comment]
This is a known limitation, but I didn't realize that `go-github` added a feature to skip validation. The [version that we vendor](https://github.com/google/go-github/blob/7462feb2032c2da9e3b85e9b04e6853a6e9e14ca/github/messages.go#L142) doesn't have that.

If you're running from source, you can try updating the dependency yourself by running `./godelw run-dep -- ensure -update github.com/google/go-github`. Otherwise, I'll put up a PR to upgrade this dependency and then you can try with the latest snapshot Docker image.

**Comment by erikkerber** [comment]
🙏 🙏 

Glad it was only a dependency version nuance that was behind the behavior I was observing!
