### ISSUE TITLE
Self-hosted installation, not as Github App?

### ISSUE THREAD

**Issue by okainov** [palantir/bulldozer#257]
I'm looking for auto-merge tools to use in our team and I wonder is it possible to run Bulldozer "on premise" using only token and not as Github app? The reason is that Github apps are not allowed in our private org, but we can interact with PRs and repos via API or directly via `git`.

**Comment by bluekeyes** [comment]
Running a self-hosted/on-premise/private instance of Bulldozer is the only option right now, as we do not offer a shared public instance of the app. You can find some more information about running your own in the [Deployment](https://github.com/palantir/bulldozer#deployment) section of the README. We're happy to answer questions if there are any missing or unclear steps.

Note that a "GitHub App" is primarily an authentication method. You can [create](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app) private apps owned by an organization that can only be installed on repositories in that organization. In this sense, there isn't much difference between using an app and using a personal access token to make API requests. The app is actually more secure, because the permissions are more granular, are limited to a specific organization and repositories, and the app tokens expire regularly.

Bulldozer is tightly coupled to the app authentication model, so supporting regular tokens is something we're unlikely to add. I suggest discussing the "no apps" policy with your organization admins to see if they are willing to create a private, organization-owned app for Bulldozer.

**Comment by okainov** [comment]
>Note that a "GitHub App" is primarily an authentication method. You can create private apps owned by an organization that can only be installed on repositories in that organization. In this sense, there isn't much difference between using an app and using a personal access token to make API requests. The app is actually more secure, because the permissions are more granular, are limited to a specific organization and repositories, and the app tokens expire regularly.

Unfortunately this is not an option, because in my company our internal organization is owned by IT team and they don't allow Github apps at all. The only option I have is acting as a user with user token/PAT.

**Comment by bluekeyes** [comment]
If you must use a personal access token, I don't think Bulldozer will be an option for you.

[Kodiak](https://kodiakhq.com/), which is another auto-merge tool, maintains a [table of some alternate implementations](https://kodiakhq.com/docs/prior-art-and-alternatives) (including Bulldozer). The comparison doesn't include the authentication method, but maybe one of those other services will work with your restrictions.
