### ISSUE TITLE
Incompatible to Github Enterprise

### ISSUE THREAD

**Issue by jimjaeger** [palantir/bulldozer#260]
Hello,

I tried bulldozer versions with Github enterprise but none of them worked. Here what I found:
- All downloadable binary versions I tried 1.10, 1.12, 1.13 1.13.1 fail to download the config .bulldozer.yml from a repo  
- A compiled version from the latest develop branch could download the config from the repo but fail later to retrieve the checkstatus information due to missing preview header.

I checked the go-github source and found a change that removed the preview header. After I added the header and compiled it, bulldozer works again with GHE.

I started a conversation with go-github to become it compatible with GHE again. 
Can you please work with go-github owner on a solution? Thanks.

Change in go-github: https://github.com/google/go-github/pull/1636
Coversation about make compatible again: https://github.com/google/go-github/issues/2082

**Comment by bluekeyes** [comment]
Hey @jimjaeger, I'm sorry you've had trouble getting Bulldozer to work with GitHub Enterprise. Can you please share the version of GitHub Enterprise you are using as well as the error you saw when you tried the latest release version of Bulldozer?

We run Bulldozer against GitHub Enterprise at Palantir and all of the released versions work in our environment. We're currently using Bulldozer 1.13.2 with GitHub Enterprise 3.1 and have not seen any issues.

As you noted, the latest versions of `google/go-github` removed support for Checks API preview headers that are required in older versions of GitHub Enterprise. Starting with the next release of Bulldozer, we plan to support only GitHub Enterprise 3.0 and newer, which I believe do not require the preview header. The latest released version (1.13.2) still includes the preview header (it uses `v32` of `google/go-github`) and should be compatible with all supported versions of GitHub Enterprise.

**Comment by jimjaeger** [comment]
It is GitHub Enterprise Server 2.22.18 - a version from July, 27, 2021. Ok thanks for the information. I tried the latest develop and it did not work. I will try again and let you the error know.

**Comment by asvoboda** [comment]
I totally understand it is frustrating that Bulldozer on develop isn't working.

However, @jimjaeger, GHE 2.22 is EOL and will be unsupported in a few weeks according to [Github](https://docs.github.com/en/enterprise-server@2.22/admin/release-notes). I suspect an older version of Bulldozer will work just fine (since we used to run 2.22 internally as well).

I think it would probably be useful to share some redacted configuration and logs to verify where the problem is located and help solve the issue you're seeing.

**Comment by jimjaeger** [comment]
@asvoboda I sent you the logs for the 2 issues above via email.

**Comment by asvoboda** [comment]
Spoke via email. I think the problem here is twofold:

1. On latest develop we have a new feature documented in the README from #256, but not part of a release just yet. This means that the older release of 1.13.x fail to parse the unknown option.

2. Latest develop drops support for GHE 2.22.x. 

The combination of both of these is confusing. However, using the example config in https://github.com/palantir/bulldozer/blob/develop/config/examples/standard.bulldozer.v1.yml on 1.13.2 should work just fine out of the box on an older GHE installation.

**Comment by asvoboda** [comment]
@jimjaeger let me know if you need anything else here. I think this is solved?
