### ISSUE TITLE
FR: allow configurable message upon merging

### ISSUE THREAD

**Issue by sjrand** [palantir/bulldozer#35]
Currently, the string "Automatically merged via Bulldozer!" is hardcoded in https://github.com/palantir/bulldozer/blob/master/github/github.go#L351.

There would be more room for amusing messages if this were configurable.

**Comment by bluekeyes** [comment]
How would you feel if there was no message at all?

One of the things I'm looking at is converting Bulldozer to the new GitHub App format, which means it will be able to act as itself instead of as a normal user. In this world, merge emails would say "Merged by Bulldozer [Bot]" or similar, which could make the comment unnecessary. If it worked like this, would you still want a configurable comment for utility and/or fun?

**Comment by sjrand** [comment]
Eh, obviously this is super low priority. If it's more than 10 minutes of work to do in the app format, then not worth it.

**Comment by ungureanuvladvictor** [comment]
@bluekeyes i was looking at https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button and I don't think it is enabled for GitHub Apps. If you look at https://developer.github.com/v3/pulls/#get-if-a-pull-request-has-been-merged there is a small `i` next to the title to indicate if a certain endpoint is enabled for GitHub Apps.

I think moving Bulldozer to an app will take a while until GitHub enables the required endpoint. Other options would be to use https://developer.github.com/v3/repos/merging/#perform-a-merge but I think this does not support multiple merge strategies.

**Comment by asvoboda** [comment]
Now that Bulldozer is a GHE app this merge message is no longer needed to let users know PRs were merged by a bot and not a human's oauth token.
