### ISSUE TITLE
Add special "merge action" which comments instead of merging

### ISSUE THREAD

**Issue by snuggie12** [palantir/bulldozer#352]
Tools like atlantis for terraform provisioning already handle merging a PR but is triggered with the comment "atlantis apply". Could this be implemented with bulldozer?

There are some complications to this. You would have to make sure after some amount of time that it is actually merged. They can take a while so I don't know the best way to handle that but if there was a failure to apply the terraform you wouldn't want bulldozer to keep commenting. Maybe it's realistic to add a label before commenting and don't try again unless the comment has been cleared?

**Comment by bluekeyes** [comment]
Hey @snuggie12, thanks for suggesting this but unfortunately, I don't think this is a feature we will implement. The core functionality of Bulldozer is merging PRs, so I want to focus on that, instead of adding ways that Bulldozer can trigger other tools.

There might be other existing bots or GitHub actions that can leave comments in response to events, but if not, I think this would be relatively straightforward to build as a custom application that responds to Github events.
