### ISSUE TITLE
Ability to wait for non required checks to pass before merging

### ISSUE THREAD

**Issue by ryanmcnamara** [palantir/bulldozer#37]
It would be nice if there was a way to wait for all (or possibly some) not required checks to pass before merging. Perhaps a config option like `require-all-status-checks`, that defaults to false for backcompat.

The use case is that there are times where a human doesn't want to be forced to wait for a status
 check to pass, but does want bulldozer to wait

**Comment by ryanmcnamara** [comment]
@ungureanuvladvictor for thoughts

**Comment by ryanmcnamara** [comment]
I'm going to implement this soon, would like approval for a configuration option from maybe @ungureanuvladvictor before I start

**Comment by bluekeyes** [comment]
@ajlake and I talked about this earlier today and think we'll be able to support it in the upcoming Bulldozer 1.0 update we're working on: there will be a configuration option to list additional status checks that Bulldozer should wait for.

I think waiting for all checks doesn't work, because there's always a race condition between how long Bulldozer decides to wait before merging and when a new status is posted. Having an explicit list of checks (merged with the ones from GitHub) should solve that part.

**Comment by bluekeyes** [comment]
This is implemented in Bulldozer 1.0 via the `required_statuses` option ([code](https://github.com/palantir/bulldozer/blob/develop/bulldozer/config_v1.go#L51)), which can appear in the `merge` block.
