### ISSUE TITLE
Whitelist/Blacklist based on target branch

### ISSUE THREAD

**Issue by bassjacob** [palantir/bulldozer#86]
Hi,

Thanks for releasing this, it's almost exactly what I need. One workflow I have seems to require a workaround, which is whitelisting/blacklisting based on the target branch of the PR. For context, we want PR's into the production environment not be to squashed, but all other PR's to be.

I've dealt with this by whitelisting labels and only applying the label to branches that should be dealt with, but it would be helpful to be able to whitelist target branches OR if it was possible to apply merge strategies based on the target branch?

I think another workaround I could apply would be to run two bulldozer apps side-by-side, but that's also a pretty big burden.

If it's something you're open to, I'd be happy to take a shot at developing the feature.

Either way, thanks for the tool :+1:

**Comment by bluekeyes** [comment]
I think whitelisting or blacklisting based on target branch makes sense as a feature. We originally thought this workflow could be supported by having Bulldozer read the configuration from the target branch, rather than the default branch, but that's hard to maintain if you ever merge the branches into each other.

If you want to try adding this yourself, take a look at the `bulldozer.Signals` type and the `IsPRBlacklisted` and `IsPRWhitelisted` methods in `bulldozer/evaluate.go`.

A future extension might be the concept of "merge rules" where you can apply fully different settings to different branches, but let's keep things simple to start.
