### ISSUE TITLE
bulldozer commit messages are inconsistent

### ISSUE THREAD

**Issue by iamdanfox** [palantir/bulldozer#93]
When a PR containing multiple commits is merged (using squash+merge), bulldozer uses the PR title as the commit message on develop.

When a PR containing a _single_ commit is merged (using squash+merge), the commit message of that single commit appears on develop, not the PR title. This is inconsistent.

It's particularly annoying because we enforce a convention of prefixing PRs with `[fix]` `[improvement]` etc in some of our OSS repos, which then get discarded. 

Example: https://github.com/palantir/conjure-java/commit/8bf6a57b5883e95ed52737c087b4bb453b023f20

**Comment by bluekeyes** [comment]
Bulldozer currently does not specify a title when merging pull requests, so what you are seeing is the default GitHub behavior for merging PRs with one or multiple commits; you should see the same thing using the UI to merge.

We originally made the decision to match the GitHub behavior, but I see the argument that Bulldozer should always use the PR title for consistency and because it provide an easy way for users to control the end result.
