### ISSUE TITLE
Unable to Merge when GitHub Branch Protection Push Restrictions Enabled

### ISSUE THREAD

**Issue by BrianChristie** [palantir/bulldozer#98]
Is there any current workarounds to use Bulldozer when `Restrict who can push to matching branches` is enabled on GitHub?

From looking at other projects, it appears it's currently impossible as GitHub does not provide a way to give push permission to the Bulldozer GitHub App directly, only user accounts or groups can be selected.

Some projects have worked around this by having a 'real' user account for the bot to use in this situation.

- Same issue in Renovate: https://github.com/renovatebot/renovate/issues/846
- Similar issue in dependabot: https://github.com/dependabot/feedback/issues/86

Thanks!

**Comment by bluekeyes** [comment]
Internally, we recommend avoiding push restrictions for this reason. We use [policy-bot](https://github.com/palantir/policy-bot) to implement approval restrictions as a required status check, which solves most of the problems we'd otherwise use push restrictions to solve. But this isn't a great solution for everyone, as it requires running a second app and doesn't enforce exactly the same thing.

I don't know of any other workaround at the moment (and I'd really like GitHub to just allow bot users to exist in that restrictions list), but adding an option to configure an OAuth token to use for merges sounds like an acceptable feature until that day. For simplicity, we'd probably use that token for all merges if it is configured, rather than only using it if the repository has push restrictions.
